version: '3'
services:
  react-webapp:
    build: ./react-webapp
    volumes:
      - ./react-webapp:/usr/src/app
    ports:
      - "${REACT_PORT}:3000"
    depends_on:
      - python-api-server

  python-api-server:
    build: ./python-api-server
    volumes:
      - ./python-api-server:/usr/src/app
    ports:
      - "${API_PORT}:5000"