version: '3'
services:
  # react-webapp:
  #   build: ./react-webapp
  #   volumes:
  #     - ./react-webapp:/usr/src/app
  #   ports:
  #     - "${REACT_PORT}:3000"
  #   depends_on:
  #     - python-api-server

  python-api-server:
    build: ./python-api-server
    volumes:
      - ./python-api-server:/usr/src/app
    ports:
      - "${API_PORT}:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@db:5432/${DB_NAME}

  db:
    image: bitnami/postgresql:11-debian-10
    restart: always
    environment:
      POSTGRESQL_DATABASE: ${DB_NAME}
      POSTGRES_USER: postgres
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5